live_config_reload = true

[colors]
draw_bold_text_with_bright_colors=true

[colors.bright]
black = "#6272a4"
blue = "#d6acff"
cyan = "#a4ffff"
green = "#69ff94"
magenta = "#ff92df"
red = "#ff6e6e"
white = "#ffffff"
yellow = "#ffffa5"

[colors.cursor]
cursor = "#ECEFF4"
text = "#3B4252"

[colors.footer_bar]
background = "#282a36"
foreground = "#f8f8f2"

[colors.hints.end]
background = "#282a36"
foreground = "#f1fa8c"

[colors.hints.start]
background = "#f1fa8c"
foreground = "#282a36"

[colors.line_indicator]
background = "None"
foreground = "None"

[colors.normal]
black = "#21222c"
blue = "#bd93f9"
cyan = "#8be9fd"
green = "#50fa7b"
magenta = "#ff79c6"
red = "#ff5555"
white = "#f8f8f2"
yellow = "#f1fa8c"

[colors.primary]
background = "0x191919"
foreground = "0xdfbf8e"

[colors.search.focused_match]
background = "#ffb86c"
foreground = "#44475a"

[colors.search.matches]
background = "#50fa7b"
foreground = "#44475a"

[colors.selection]
background = "#44475a"
text = "CellForeground"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"

[font]
size = 11.0

[font.bold]
family = "MesloLGS NF"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "MesloLGS NF"
style = "Italic"

[font.normal]
family = "MesloLGS NF"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

# [schemes.dracula.bright]
# black = "#6272a4"
# blue = "#d6acff"
# cyan = "#a4ffff"
# green = "#69ff94"
# magenta = "#ff92df"
# red = "#ff6e6e"
# white = "#ffffff"
# yellow = "#ffffa5"

# [schemes.dracula.cursor]
# cursor = "#ECEFF4"
# text = "#3B4252"

# [schemes.dracula.footer_bar]
# background = "#282a36"
# foreground = "#f8f8f2"

# [schemes.dracula.hints.end]
# background = "#282a36"
# foreground = "#f1fa8c"

# [schemes.dracula.hints.start]
# background = "#f1fa8c"
# foreground = "#282a36"

# [schemes.dracula.line_indicator]
# background = "None"
# foreground = "None"

# [schemes.dracula.normal]
# black = "#21222c"
# blue = "#bd93f9"
# cyan = "#8be9fd"
# green = "#50fa7b"
# magenta = "#ff79c6"
# red = "#ff5555"
# white = "#f8f8f2"
# yellow = "#f1fa8c"

# [schemes.dracula.primary]
# background = "0x191919"
# foreground = "0xdfbf8e"

# [schemes.dracula.search.focused_match]
# background = "#ffb86c"
# foreground = "#44475a"

# [schemes.dracula.search.matches]
# background = "#50fa7b"
# foreground = "#44475a"

# [schemes.dracula.selection]
# background = "#44475a"
# text = "CellForeground"

# [schemes.dracula.vi_mode_cursor]
# cursor = "CellForeground"
# text = "CellBackground"

# [schemes.main.colors.bright]
# black = "0x928374"
# blue = "0x7daea3"
# cyan = "0x89b482"
# green = "0xa9b665"
# magenta = "0xd3869b"
# red = "0xea6962"
# white = "0xdfbf8e"
# yellow = "0xe3a84e"

# [schemes.main.colors.normal]
# black = "0x665c54"
# blue = "0x7daea3"
# cyan = "0x89b482"
# green = "0xa9b665"
# magenta = "0xd3869b"
# red = "0xea6962"
# white = "0xdfbf8e"
# yellow = "0xe78a4e"

# [schemes.main.colors.primary]
# background = "0x191919"
# foreground = "0xdfbf8e"

# [[schemes.tokyo-night.indexed_colors]]
# color = "0xff9e64"
# index = 16

# [[schemes.tokyo-night.indexed_colors]]
# color = "0xdb4b4b"
# index = 17

# [schemes.tokyo-night.bright]
# black = "0x414868"
# blue = "0x7aa2f7"
# cyan = "0x7dcfff"
# green = "0x9ece6a"
# magenta = "0xbb9af7"
# red = "0xf7768e"
# white = "0xc0caf5"
# yellow = "0xe0af68"

# [schemes.tokyo-night.normal]
# black = "0x15161e"
# blue = "0x7aa2f7"
# cyan = "0x7dcfff"
# green = "0x9ece6a"
# magenta = "0xbb9af7"
# red = "0xf7768e"
# white = "0xa9b1d6"
# yellow = "0xe0af68"

# [schemes.tokyo-night.primary]
# background = "0x1a1b26"
# foreground = "0xc0caf5"

# [schemes.tokyo-night-storm.bright]
# black = "#444b6a"
# blue = "#7da6ff"
# cyan = "#0db9d7"
# green = "#b9f27c"
# magenta = "#bb9af7"
# red = "#ff7a93"
# white = "#acb0d0"
# yellow = "#ff9e64"

# [schemes.tokyo-night-storm.normal]
# black = "#32344a"
# blue = "#7aa2f7"
# cyan = "#449dab"
# green = "#9ece6a"
# magenta = "#ad8ee6"
# red = "#f7768e"
# white = "#9699a8"
# yellow = "#e0af68"

# [schemes.tokyo-night-storm.primary]
# background = "#24283b"
# foreground = "#a9b1d6"

[scrolling]
# draw_bold_text_with_bright_colors = false
history = 10000

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
dynamic_title = true
opacity = 0.9

[window.padding]
x = 2
y = 2
