return {
  {
    "supermaven-inc/supermaven-nvim",
    -- {
    --   "yetone/avante.nvim",
    --   -- if you want to build from source then do `make BUILD_FROM_SOURCE=true`
    --   -- ⚠️ must add this setting! ! !
    --   build = vim.fn.has("win32") ~= 0 and "powershell -ExecutionPolicy Bypass -File Build.ps1 -BuildFromSource false"
    --     or "make",
    --   event = "VeryLazy",
    --   version = false, -- Never set this value to "*"! Never!
    --   ---@module 'avante'
    --   ---@type avante.Config
    --   opts = {
    --     -- add any opts here
    --     -- this file can contain specific instructions for your project
    --     instructions_file = "avante.md",
    --     -- for example
    --     provider = "claude",
    --     providers = {
    --       claude = {
    --         endpoint = "https://api.anthropic.com",
    --         model = "claude-sonnet-4-20250514",
    --         timeout = 30000, -- Timeout in milliseconds
    --         extra_request_body = {
    --           temperature = 0.75,
    --           max_tokens = 20480,
    --         },
    --       },
    --     },
    --   },
    --   dependencies = {
    --     "nvim-lua/plenary.nvim",
    --     "MunifTanjim/nui.nvim",
    --     --- The below dependencies are optional,
    --     "ibhagwan/fzf-lua", -- for file_selector provider fzf
    --     {
    --       -- support for image pasting
    --       "HakonHarnes/img-clip.nvim",
    --       event = "VeryLazy",
    --       opts = {
    --         -- recommended settings
    --         default = {
    --           embed_image_as_base64 = false,
    --           prompt_for_file_name = false,
    --           drag_and_drop = {
    --             insert_mode = true,
    --           },
    --           -- required for Windows users
    --           use_absolute_path = true,
    --         },
    --       },
    --     },
    --     {
    --       -- Make sure to set this up properly if you have lazy=true
    --       "MeanderingProgrammer/render-markdown.nvim",
    --       opts = {
    --         file_types = { "markdown", "Avante" },
    --       },
    --       ft = { "markdown", "Avante" },
    --     },
    --   },
    -- },
  },
}
