/**
 * Git Workflow — /commit, /pr, /commit-and-pr
 *
 * Smart commits grouped by logical change with conventional commit messages.
 * PR creation via gh CLI with clean descriptions.
 *
 * All commands accept optional context to scope what gets committed:
 *   /commit only the auth module
 *   /commit-and-pr main only dark mode changes
 *   /commit-and-pr main #42 just the API routes
 */

import type { ExtensionAPI } from "@mariozechner/pi-coding-agent";

const NO_AI_RULE = `**No AI attribution** — NEVER add "generated by", "co-authored-by" with any AI/LLM name, "claude", "copilot", "gpt", "cursor", or any agent/AI mention in commits, PR title, or PR body.`;

const COMMIT_INSTRUCTIONS = (context?: string) => {
	let prompt = `Inspect and commit current changes. Follow these rules strictly:

1. Run \`git status\` and \`git diff\` (include \`--staged\` if needed) to inspect all changes
2. For untracked files, read their content to understand what they do
3. **Group** related files into logical commits (e.g. all files for one feature together)
4. Use **conventional commit** format: \`type(scope): message\`
   - Types: feat, fix, chore, refactor, docs, style, test, perf, ci, build
   - Scope is optional but recommended when clear
   - Message must be minimal, lowercase, no trailing period
5. ${NO_AI_RULE}
6. **Stage selectively** — \`git add <specific files>\` for each group, then \`git commit -m "..."\`
7. **Show the plan first** — list each planned commit with its files and message, then wait for my confirmation before executing
8. If a single commit makes more sense than multiple, that's fine — don't split unnecessarily`;

	if (context) {
		prompt += `\n\n**SCOPE**: The user wants to commit ONLY: "${context}"
- If the scope is a directory path (e.g. "frontend", "backend"), use \`git -C ${context.split(/\s+/)[0]}\` if it's a separate git repo, or scope with \`git add ${context.split(/\s+/)[0]}/\` if it's a subdirectory in the current repo
- Check for a .git directory inside the path to determine if it's a nested repo
- Carefully review all changes but ONLY stage and commit files related to this scope
- Leave all other changes unstaged
- If no changes match the scope, say so and list what IS changed instead`;
	}

	return prompt;
};

const PR_INSTRUCTIONS = (base: string, issue?: string, context?: string, dir?: string) => {
	const gitCmd = dir ? `git -C ${dir}` : "git";
	const ghCmd = dir ? `cd ${dir} && gh` : "gh";

	let prompt = `Create a pull request against \`${base}\` using the \`gh\` CLI.`;

	if (dir) {
		prompt += `\n\n**DIRECTORY**: The git repo is in \`${dir}/\`. All git and gh commands must target that directory.
- Use \`${gitCmd}\` for git commands
- Use \`${ghCmd}\` for gh commands (gh must run from inside the repo)`;
	}

	prompt += `

1. Run \`${gitCmd} log ${base}..HEAD --oneline\` and \`${gitCmd} diff ${base}..HEAD --stat\` to understand changes
2. Read the changed files to understand what was modified
3. Generate a **clean PR title** using conventional format (feat, fix, chore, etc.)
4. Generate a **concise PR body** with these sections:
   - **What changed** — brief summary of the changes
   - **Why** — motivation/context (if not obvious)
   - **Test coverage** — a checklist of things to test, formatted as:
     \`\`\`
     ## Test Coverage
     - [ ] Description of test scenario 1
     - [ ] Description of test scenario 2
     - [ ] Edge case to verify
     \`\`\`
     Include happy paths, edge cases, error scenarios, and any regressions to watch for.
     Be specific — reference actual user flows, API endpoints, or UI interactions affected.
5. ${NO_AI_RULE}
6. Push the current branch first if needed: \`${gitCmd} push -u origin HEAD\`
7. **Show me the title and body first**, wait for confirmation, then run \`${ghCmd} pr create --base ${base} --title "..." --body "..."\``;

	if (issue) {
		prompt += `\n7. Include \`Closes ${issue}\` at the end of the PR body`;
	}

	if (context) {
		prompt += `\n\n**FOCUS**: The PR description should emphasize: "${context}"`;
	}

	return prompt;
};

const COMMIT_AND_PR_INSTRUCTIONS = (base: string, issue?: string, context?: string, dir?: string) => {
	const gitCmd = dir ? `git -C ${dir}` : "git";
	const ghCmd = dir ? `cd ${dir} && gh` : "gh";

	let prompt = `First commit changes, then create a pull request. Do this in two steps:`;

	if (dir) {
		prompt += `\n\n**DIRECTORY**: The git repo is in \`${dir}/\`. All git and gh commands must target that directory.
- Use \`${gitCmd}\` for git commands
- Use \`${ghCmd}\` for gh commands (gh must run from inside the repo)`;
	}

	prompt += `

## Step 1 — Commit

${COMMIT_INSTRUCTIONS(context)}

## Step 2 — Pull Request (after all commits are done)

1. Push branch: \`${gitCmd} push -u origin HEAD\`
2. Run \`${gitCmd} log ${base}..HEAD --oneline\` and \`${gitCmd} diff ${base}..HEAD --stat\`
3. Read the changed files to understand what was modified
4. Generate a clean PR title (conventional format) and concise body with these sections:
   - **What changed** — brief summary
   - **Why** — motivation/context
   - **Test coverage** — a checklist of things to test:
     \`\`\`
     ## Test Coverage
     - [ ] Test scenario description
     - [ ] Edge case to verify
     \`\`\`
     Include happy paths, edge cases, error scenarios, and regressions to watch for.
     Be specific — reference actual user flows, API endpoints, or UI interactions.
5. ${NO_AI_RULE}
6. **Show me the PR title and body**, wait for confirmation, then run \`${ghCmd} pr create --base ${base} --title "..." --body "..."\``;

	if (issue) {
		prompt += `\n6. Include \`Closes ${issue}\` at the end of the PR body`;
	}

	return prompt;
};

function parseArgs(args?: string): { base?: string; issue?: string; context?: string; dir?: string } {
	const raw = args?.trim() || "";
	if (!raw) return {};

	// Extract #issue references
	const issueMatch = raw.match(/#\d+/);
	const issue = issueMatch?.[0];

	// Remove the issue from the string
	let rest = raw.replace(/#\d+/g, "").trim();

	// First non-flag word that looks like a branch name is the base
	// Branch names: alphanumeric, dashes, slashes, dots, underscores
	const words = rest.split(/\s+/);
	let base: string | undefined;
	let contextWords: string[] = [];

	for (let i = 0; i < words.length; i++) {
		const w = words[i];
		// If it looks like a branch name and we haven't found one yet
		if (!base && /^[a-zA-Z0-9][a-zA-Z0-9._\/-]*$/.test(w) && !isCommonWord(w)) {
			base = w;
		} else {
			contextWords.push(w);
		}
	}

	const context = contextWords.join(" ").trim() || undefined;

	// Detect if context starts with a directory path
	const dir = detectDir(context);

	return { base, issue, context, dir };
}

/** Words that are clearly context, not branch names */
function isCommonWord(w: string): boolean {
	const common = new Set([
		"only", "just", "the", "all", "for", "with", "without", "except",
		"add", "fix", "update", "remove", "delete", "change", "refactor",
		"include", "exclude", "skip", "ignore", "related", "to", "from",
		"and", "or", "not", "no", "in", "of", "a", "an", "but",
	]);
	return common.has(w.toLowerCase());
}

/** Extract a directory path from the start of context, if it exists on disk */
function detectDir(context?: string): string | undefined {
	if (!context) return undefined;
	const candidate = context.split(/\s+/)[0].replace(/\/+$/, "");
	// Check synchronously if it's a directory
	try {
		const fs = require("fs");
		if (fs.statSync(candidate).isDirectory()) return candidate;
	} catch {}
	return undefined;
}

/** Check for git changes, trying subdirectory if context looks like a path */
async function hasChanges(pi: ExtensionAPI, context?: string, dir?: string): Promise<boolean> {
	const target = dir || (context ? context.split(/\s+/)[0].replace(/\/+$/, "") : undefined);

	if (target) {
		// Try git status in the subdirectory (nested git repo)
		try {
			const { stdout } = await pi.exec("git", ["-C", target, "status", "--porcelain"]);
			if (stdout.trim()) return true;
		} catch {}
		// Try scoping to the path within the current repo (monorepo subdir)
		try {
			const { stdout } = await pi.exec("git", ["status", "--porcelain", "--", target]);
			if (stdout.trim()) return true;
		} catch {}
	}

	// Fallback: check the whole repo
	try {
		const { stdout } = await pi.exec("git", ["status", "--porcelain"]);
		if (stdout.trim()) return true;
	} catch {}

	return false;
}

export default function (pi: ExtensionAPI) {
	pi.registerCommand("commit", {
		description: "Commit changes. Usage: /commit [path or context]",
		handler: async (args, ctx) => {
			const context = args?.trim() || undefined;
			const dir = detectDir(context);
			if (!(await hasChanges(pi, context, dir))) {
				ctx.ui.notify("No changes to commit.", "warning");
				return;
			}
			pi.sendUserMessage(COMMIT_INSTRUCTIONS(context));
		},
	});

	pi.registerCommand("pr", {
		description: "Create a PR. Usage: /pr <base> [#issue] [context]",
		handler: async (args, ctx) => {
			const { base, issue, context, dir } = parseArgs(args);
			if (!base) {
				ctx.ui.notify("Usage: /pr <base-branch> [#issue] [context]", "warning");
				return;
			}
			pi.sendUserMessage(PR_INSTRUCTIONS(base, issue, context, dir));
		},
	});

	pi.registerCommand("commit-and-pr", {
		description: "Commit then PR. Usage: /commit-and-pr <base> [#issue] [context]",
		handler: async (args, ctx) => {
			const { base, issue, context, dir } = parseArgs(args);
			if (!base) {
				ctx.ui.notify("Usage: /commit-and-pr <base-branch> [#issue] [context]", "warning");
				return;
			}

			if (!(await hasChanges(pi, context, dir))) {
				ctx.ui.notify("No changes to commit. Use /pr instead.", "warning");
				return;
			}

			pi.sendUserMessage(COMMIT_AND_PR_INSTRUCTIONS(base, issue, context, dir));
		},
	});
}
