require('globals')
require('sets')
require('plugins')
require('keymappings')
require('lv-telescope')
require('lv-nvimtree')
require('lv-comment')
require('lv-surround')
require('lv-compe')
require('lv-treesitter')
require('lv-autopairs')
require('lv-barbar')
require('lv-lsp-rooter')

require('lsp')
require('lsp.vue-ls')
require('lsp.js-ts-ls')
require('lsp.efm-general-ls')
