#!/bin/sh
HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=1000000
SAVEHIST=1000000
export PATH="$HOME/.local/bin":$PATH
export MANPAGER='nvim +Man!'
export MANWIDTH=999
export PATH=$HOME/.cargo/bin:$PATH
export PATH=$HOME/.local/share/gem/ruby/3.0.0/bin:$PATH
export MOZ_ENABLE_WAYLAND=1
export EDITOR=nvim
export LD_PRELOAD=/usr/lib/libv4l/v4l2convert.so
eval "$(zoxide init zsh)"
# eval "`pip completion --zsh`"
