#!/bin/bash

# JankyBorders Configuration
# Matching Sway window borders style

# Colors from your Sway config:
# focused_bgcolor = $c2 (#d79921)
# inactive_bgcolor = $c5 (#342f73)
# unfocused_bgcolor = $c4 (#333142)

options=(
  style=round
  width=2.0
  hidpi=on
  active_color=0xffd79921    # Focused: yellow/gold (#d79921) from Sway
  inactive_color=0xff333142  # Unfocused: dark purple (#333142) from Sway
)

borders "${options[@]}"
