return {
  graphql = require("rielj.lsp.servers.graphql"),
  rust_analyzer = require("rielj.lsp.servers.rust_analyzer"),
  gopls = require("rielj.lsp.servers.gopls"),
  html = require("rielj.lsp.servers.html"),
  htmx = require("rielj.lsp.servers.htmx"),
  tailwindcss = require("rielj.lsp.servers.tailwindcss"),
  cssls = require("rielj.lsp.servers.cssls"),
  jsonls = require("rielj.lsp.servers.jsonls"),
  yamlls = require("rielj.lsp.servers.yamlls"),
  cmake = (1 == vim.fn.executable("cmake-language-server")),
  solidity_ls_nomicfoundation = true,
  tflint = true,
  terraformls = true,
  bashls = true,
  bufls = true,
  eslintls = false,
  eslint = false,
  -- svelte = true,
  svelte = require("rielj.lsp.servers.svelte"),
  templ = true,
  dockerls = true,
  pyright = true,
  prismals = true,
  vimls = true,
}
