vim.api.nvim_command('set guicursor=i:blinkwait200-blinkoff400-blinkon250-Cursor')
vim.api.nvim_command('set relativenumber')
vim.api.nvim_command('set nohlsearch')
vim.api.nvim_command('set hidden')
vim.api.nvim_command('set noerrorbells')
vim.api.nvim_command('set tabstop=2 softtabstop=2')
vim.api.nvim_command('set shiftwidth=2')
vim.api.nvim_command('set expandtab')
vim.api.nvim_command('set smartindent')
vim.api.nvim_command('set nu')
vim.api.nvim_command('set nowrap')
vim.api.nvim_command('set noswapfile')
vim.api.nvim_command('set nobackup')
vim.api.nvim_command('set undodir=~/.vim/undodir')
vim.api.nvim_command('set undofile')
vim.api.nvim_command('set incsearch')
vim.api.nvim_command('set termguicolors')
vim.api.nvim_command('set scrolloff=10')
vim.api.nvim_command('set signcolumn=yes')
vim.api.nvim_command('set isfname+=@-@')
vim.api.nvim_command('set cmdheight=1')
vim.api.nvim_command('set updatetime=50')
vim.api.nvim_command('set shortmess+=c')
-- vim.api.nvim_command('set colorcolumn=80')

vim.api.nvim_command('set wildmode=longest,list,full')
vim.api.nvim_command('set wildmenu')
vim.api.nvim_command('set wildignore+=*.pyc')
vim.api.nvim_command('set wildignore+=*_build/*')
vim.api.nvim_command('set wildignore+=**/node_modules/*')
vim.api.nvim_command('set wildignore+=**/.git/*')

